apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: "RuntimeDefault"
        runAsNonRoot: true
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        # Delete any existing contents of the directory if it exists.
        #
        # We don't just "rm -rf ${WORKSPACE_SOURCE_PATH}" because ${WORKSPACE_SOURCE_PATH} might be "/"
        # or the root of a mounted volume.
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          # Delete non-hidden files and directories
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to the nose
      type: string
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        python3 -m pip install --upgrade pip wheel
        pip3 install -r requirements.txt
        nosetests $(params.args)
      securityContext:
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: "RuntimeDefault"
        runAsNonRoot: true
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: openshift-cli-runner
  labels:
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/part-of: "ci-cd-pipeline"
spec:
  description: >
    Executes arbitrary OpenShift CLI ('oc') commands in a container.
  params:
    - name: script
      type: string
      description: The script containing the 'oc' commands to execute.
  steps:
    - name: run-oc-script
      image: quay.io/openshift/origin-cli:latest # Reliable image with the 'oc' command
      script: |
        #!/usr/bin/env bash
        set -e # Exit immediately if a command exits with a non-zero status
        echo "Running OpenShift script:"
        
        # The script parameter holds the command block
        eval "${script}"